# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: parser.proto for package 'twittertext'
# Original file comments:
# We're using proto3 syntax

require 'grpc'
require 'parser_pb'

module Twittertext
  module TwitterText
    # This is the service for our API
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'twittertext.TwitterText'

      # We have a mehtod called 'Parse' which takes
      # parameter called 'TweetRequest' and returns
      # the message 'ParsedResponse'
      rpc :Parse, TweetRequest, ParsedResponse
    end

    Stub = Service.rpc_stub_class
  end
  # This is where we define the methods in this service
end
